name: Publish via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  publish:
    name: Publish via FTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
      # Popular action to deploy via FTP:
      # Docs: https://github.com/SamKirkland/FTP-Deploy-Action
      - name: Publish via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          # Build output to publish:
          local-dir: ./build/
          server-dir: /
